// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	// Patient operations
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	GetAnswerHistory(ctx context.Context, arg GetAnswerHistoryParams) ([]GetAnswerHistoryRow, error)
	GetAnswerHistoryCount(ctx context.Context, arg GetAnswerHistoryCountParams) (int64, error)
	// Doctor operations
	GetPendingReviews(ctx context.Context, arg GetPendingReviewsParams) ([]GetPendingReviewsRow, error)
	GetPendingReviewsCount(ctx context.Context, arg GetPendingReviewsCountParams) (int64, error)
	GetQuestionStatus(ctx context.Context, arg GetQuestionStatusParams) (GetQuestionStatusRow, error)
	SaveAIDraftAnswer(ctx context.Context, arg SaveAIDraftAnswerParams) (Answer, error)
	SubmitReview(ctx context.Context, arg SubmitReviewParams) (Answer, error)
}

var _ Querier = (*Queries)(nil)
