// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: medical_qa.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MedicalQAService_GenerateDraftAnswer_FullMethodName = "/medical_qa.MedicalQAService/GenerateDraftAnswer"
	MedicalQAService_ReviewAnswer_FullMethodName        = "/medical_qa.MedicalQAService/ReviewAnswer"
)

// MedicalQAServiceClient is the client API for MedicalQAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main QA service definition
type MedicalQAServiceClient interface {
	// Generate a draft answer for medical questions
	GenerateDraftAnswer(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionResponse, error)
	// Review and modify draft answer
	ReviewAnswer(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
}

type medicalQAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMedicalQAServiceClient(cc grpc.ClientConnInterface) MedicalQAServiceClient {
	return &medicalQAServiceClient{cc}
}

func (c *medicalQAServiceClient) GenerateDraftAnswer(ctx context.Context, in *QuestionRequest, opts ...grpc.CallOption) (*QuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionResponse)
	err := c.cc.Invoke(ctx, MedicalQAService_GenerateDraftAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medicalQAServiceClient) ReviewAnswer(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, MedicalQAService_ReviewAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedicalQAServiceServer is the server API for MedicalQAService service.
// All implementations must embed UnimplementedMedicalQAServiceServer
// for forward compatibility.
//
// Main QA service definition
type MedicalQAServiceServer interface {
	// Generate a draft answer for medical questions
	GenerateDraftAnswer(context.Context, *QuestionRequest) (*QuestionResponse, error)
	// Review and modify draft answer
	ReviewAnswer(context.Context, *ReviewRequest) (*ReviewResponse, error)
	mustEmbedUnimplementedMedicalQAServiceServer()
}

// UnimplementedMedicalQAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMedicalQAServiceServer struct{}

func (UnimplementedMedicalQAServiceServer) GenerateDraftAnswer(context.Context, *QuestionRequest) (*QuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDraftAnswer not implemented")
}
func (UnimplementedMedicalQAServiceServer) ReviewAnswer(context.Context, *ReviewRequest) (*ReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewAnswer not implemented")
}
func (UnimplementedMedicalQAServiceServer) mustEmbedUnimplementedMedicalQAServiceServer() {}
func (UnimplementedMedicalQAServiceServer) testEmbeddedByValue()                          {}

// UnsafeMedicalQAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedicalQAServiceServer will
// result in compilation errors.
type UnsafeMedicalQAServiceServer interface {
	mustEmbedUnimplementedMedicalQAServiceServer()
}

func RegisterMedicalQAServiceServer(s grpc.ServiceRegistrar, srv MedicalQAServiceServer) {
	// If the following call pancis, it indicates UnimplementedMedicalQAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MedicalQAService_ServiceDesc, srv)
}

func _MedicalQAService_GenerateDraftAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedicalQAServiceServer).GenerateDraftAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedicalQAService_GenerateDraftAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedicalQAServiceServer).GenerateDraftAnswer(ctx, req.(*QuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedicalQAService_ReviewAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedicalQAServiceServer).ReviewAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedicalQAService_ReviewAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedicalQAServiceServer).ReviewAnswer(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MedicalQAService_ServiceDesc is the grpc.ServiceDesc for MedicalQAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MedicalQAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medical_qa.MedicalQAService",
	HandlerType: (*MedicalQAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDraftAnswer",
			Handler:    _MedicalQAService_GenerateDraftAnswer_Handler,
		},
		{
			MethodName: "ReviewAnswer",
			Handler:    _MedicalQAService_ReviewAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medical_qa.proto",
}
