# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import medical_qa_pb2 as medical__qa__pb2


class MedicalQAServiceStub(object):
    """Main QA service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDraftAnswer = channel.unary_unary(
                '/medical_qa.MedicalQAService/GenerateDraftAnswer',
                request_serializer=medical__qa__pb2.QuestionRequest.SerializeToString,
                response_deserializer=medical__qa__pb2.QuestionResponse.FromString,
                )


class MedicalQAServiceServicer(object):
    """Main QA service definition
    """

    def GenerateDraftAnswer(self, request, context):
        """Generate a draft answer for medical questions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicalQAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDraftAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDraftAnswer,
                    request_deserializer=medical__qa__pb2.QuestionRequest.FromString,
                    response_serializer=medical__qa__pb2.QuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medical_qa.MedicalQAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MedicalQAService(object):
    """Main QA service definition
    """

    @staticmethod
    def GenerateDraftAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/medical_qa.MedicalQAService/GenerateDraftAnswer',
            medical__qa__pb2.QuestionRequest.SerializeToString,
            medical__qa__pb2.QuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
