# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medical_qa.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10medical_qa.proto\x12\nmedical_qa\"p\n\x0fQuestionRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x15\n\rquestion_text\x18\x02 \x01(\t\x12\x17\n\x0fpatient_context\x18\x03 \x01(\t\x12\x18\n\x10medical_category\x18\x04 \x01(\t\"k\n\x10QuestionResponse\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64raft_answer\x18\x02 \x01(\t\x12\x12\n\nreferences\x18\x03 \x03(\t\x12\x18\n\x10\x63onfidence_score\x18\x04 \x01(\x02\"\x7f\n\rReviewRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64raft_answer\x18\x02 \x01(\t\x12\x13\n\x0breviewer_id\x18\x03 \x01(\t\x12\x19\n\x11reviewer_comments\x18\x04 \x01(\t\x12\x13\n\x0bis_approved\x18\x05 \x01(\x08\"\x81\x01\n\x0eReviewResponse\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66inal_answer\x18\x02 \x01(\t\x12\x15\n\rreview_status\x18\x03 \x01(\t\x12\x13\n\x0breviewer_id\x18\x04 \x01(\t\x12\x18\n\x10review_timestamp\x18\x05 \x01(\t2\xaf\x01\n\x10MedicalQAService\x12R\n\x13GenerateDraftAnswer\x12\x1b.medical_qa.QuestionRequest\x1a\x1c.medical_qa.QuestionResponse\"\x00\x12G\n\x0cReviewAnswer\x12\x19.medical_qa.ReviewRequest\x1a\x1a.medical_qa.ReviewResponse\"\x00\x42\x15Z\x13llm-qa-system/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medical_qa_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023llm-qa-system/proto'
  _globals['_QUESTIONREQUEST']._serialized_start=32
  _globals['_QUESTIONREQUEST']._serialized_end=144
  _globals['_QUESTIONRESPONSE']._serialized_start=146
  _globals['_QUESTIONRESPONSE']._serialized_end=253
  _globals['_REVIEWREQUEST']._serialized_start=255
  _globals['_REVIEWREQUEST']._serialized_end=382
  _globals['_REVIEWRESPONSE']._serialized_start=385
  _globals['_REVIEWRESPONSE']._serialized_end=514
  _globals['_MEDICALQASERVICE']._serialized_start=517
  _globals['_MEDICALQASERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
